### ISSUE TITLE
Which layer to monitor

### ISSUE THREAD

**Issue by bigaidream** [bigaidream-projects/qan#15]
# Experimental Procedure

The dataset should be CIFAR-10. 

Say the CNN has 5 layers of hidden layers. The question is which layer should we use for the DQN states?

Run 5 independent experiments, each DQN monitoring a different layer. We'd like to see which layer gives the best result.

**Comment by taineleau** [comment]
May we have a discuss on Deepmind's work (https://arxiv.org/abs/1606.04474)? Their strategy to obtain a representation of a CNN's state is sophisticated.

**Comment by bigaidream** [comment]
According to [Convergent Learning: Do Different Neural Networks Learn the Same Representations?], we should only monitor the first layer (close to input).
