### ISSUE TITLE
Replace regression with a meta-momentum

### ISSUE THREAD

**Issue by bigaidream** [bigaidream-projects/qan#5]
One possible way is to explicitly use 2 GPUs: one for CNN and one for DQN. 
They can be trained asynchronously.

**Comment by bigaidream** [comment]
We don't add this extra loss anymore. We simply adopt the tradition of momentum. 

For example, we have a vector of weights after convergence [2, 3, 2] at the first episode. At the second episode, the current weight vector is [0.1, 0.3, 0.1], and the difference is [1.9, 2.7, 1.9]. Now we change the weight vector this way [0.1+ 1.9*1/00, 0.3 +2.7*1/100, 0.1 + 1.9*1/00]

**Comment by bigaidream** [comment]
@LinZichuan Estimated finish date: `2016-08-01`

**Comment by bigaidream** [comment]
Shouldn't set the meta-momentum co-efficient directly in the code. Should put it into the parameters list in the beginning of the code. 
@LinZichuan

**Comment by taineleau** [comment]
One possible way is to explicitly use 2 GPUs: one for CNN and one for DQN. 

> It may not bring any speedup if you apply such a model-parallel method.

**Comment by bigaidream** [comment]
Done.
